apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-vebz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-vebz
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-vebz
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-vebz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-vebz
    spec:
      containers:
      - image: quay.io/qijing/ex-registry-oqmp-tenant/appstudio/dc-metro-map-vebz@sha256:4f85f4f2d9cfd523b5ed8902154d2fda445ab736dbcd129a9c85be049527e99a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
