apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-vebz
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/qijing/ex-registry-oqmp-tenant/appstudio/dc-metro-map-vebz@sha256:4f85f4f2d9cfd523b5ed8902154d2fda445ab736dbcd129a9c85be049527e99a
        name: my-nodejs
        resources: {}
status: {}
